/*
 * VM Auto Scaling API
 * The VM Auto Scaling Service enables IONOS clients to horizontally scale the number of VM replicas based on configured rules. You can use VM Auto Scaling to ensure that you have a sufficient number of replicas to handle your application loads at all times.  For this purpose, create a VM Auto Scaling Group that contains the server replicas. The VM Auto Scaling Service ensures that the number of replicas in the group is always within the defined limits.   When scaling policies are set, VM Auto Scaling creates or deletes replicas according to the requirements of your applications. For each policy, specified 'scale-in' and 'scale-out' actions are performed when the corresponding thresholds are reached.
 *
 * The version of the OpenAPI document: 1-SDK.1
 * Contact: support@cloud.ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.vmautoscaling.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ionoscloud.vmautoscaling.model.ActionResource;
import com.ionoscloud.vmautoscaling.model.GroupPostEntities;
import com.ionoscloud.vmautoscaling.model.GroupProperties;
import com.ionoscloud.vmautoscaling.model.Metadata;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * A group of virtual servers where the number of replicas can be scaled automatically.
 */
@ApiModel(description = "A group of virtual servers where the number of replicas can be scaled automatically.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-25T09:34:22.361740Z[Etc/UTC]")

public class GroupPostResponse {
  
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;


  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;


  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private URI href;


  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Metadata metadata;


  public static final String SERIALIZED_NAME_PROPERTIES = "properties";
  @SerializedName(SERIALIZED_NAME_PROPERTIES)
  private GroupProperties properties;


  public static final String SERIALIZED_NAME_ENTITIES = "entities";
  @SerializedName(SERIALIZED_NAME_ENTITIES)
  private GroupPostEntities entities;


  public static final String SERIALIZED_NAME_STARTED_ACTIONS = "startedActions";
  @SerializedName(SERIALIZED_NAME_STARTED_ACTIONS)
  private List<ActionResource> startedActions = null;

  

   /**
   * The unique resource identifier.
   * @return id
  **/
  @ApiModelProperty(example = "1d67ca27-d4c0-419d-9a64-9ea42dfdd036", required = true, value = "The unique resource identifier.")

  public UUID getId() {
    return id;
  }


  public void setId(UUID id) {
    this.id = id;
  }



   /**
   * The resource type.
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "autoscaling-group", value = "The resource type.")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }



   /**
   * The absolute URL to the resource&#39;s representation.
   * @return href
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "https://api.ionos.com/autoscaling/groups/1d67ca27-d4c0-419d-9a64-9ea42dfdd036", value = "The absolute URL to the resource's representation.")

  public URI getHref() {
    return href;
  }


  public void setHref(URI href) {
    this.href = href;
  }



  public GroupPostResponse metadata(Metadata metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Metadata getMetadata() {
    return metadata;
  }


  public void setMetadata(Metadata metadata) {
    this.metadata = metadata;
  }



  public GroupPostResponse properties(GroupProperties properties) {
    
    this.properties = properties;
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @ApiModelProperty(required = true, value = "")

  public GroupProperties getProperties() {
    return properties;
  }


  public void setProperties(GroupProperties properties) {
    this.properties = properties;
  }



  public GroupPostResponse entities(GroupPostEntities entities) {
    
    this.entities = entities;
    return this;
  }

   /**
   * Get entities
   * @return entities
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GroupPostEntities getEntities() {
    return entities;
  }


  public void setEntities(GroupPostEntities entities) {
    this.entities = entities;
  }



   /**
   * Any background activity caused by this request. You can use this to track the progress of such activities.
   * @return startedActions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Any background activity caused by this request. You can use this to track the progress of such activities.")

  public List<ActionResource> getStartedActions() {
    return startedActions;
  }


  public void setStartedActions(List<ActionResource> startedActions) {
    this.startedActions = startedActions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupPostResponse groupPostResponse = (GroupPostResponse) o;
    return Objects.equals(this.id, groupPostResponse.id) && Objects.equals(this.type, groupPostResponse.type) && Objects.equals(this.href, groupPostResponse.href) && Objects.equals(this.metadata, groupPostResponse.metadata) && Objects.equals(this.properties, groupPostResponse.properties) && Objects.equals(this.entities, groupPostResponse.entities) && Objects.equals(this.startedActions, groupPostResponse.startedActions);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupPostResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");

    sb.append("    type: ").append(toIndentedString(type)).append("\n");

    sb.append("    href: ").append(toIndentedString(href)).append("\n");

    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");

    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");

    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");

    sb.append("    startedActions: ").append(toIndentedString(startedActions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

