/*
 * VM Auto Scaling API
 * The VM Auto Scaling Service enables IONOS clients to horizontally scale the number of VM replicas based on configured rules. You can use VM Auto Scaling to ensure that you have a sufficient number of replicas to handle your application loads at all times.  For this purpose, create a VM Auto Scaling Group that contains the server replicas. The VM Auto Scaling Service ensures that the number of replicas in the group is always within the defined limits.   When scaling policies are set, VM Auto Scaling creates or deletes replicas according to the requirements of your applications. For each policy, specified 'scale-in' and 'scale-out' actions are performed when the corresponding thresholds are reached.
 *
 * The version of the OpenAPI document: 1-SDK.1
 * Contact: support@cloud.ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.vmautoscaling.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ionoscloud.vmautoscaling.model.GroupPolicy;
import com.ionoscloud.vmautoscaling.model.GroupPropertiesDatacenter;
import com.ionoscloud.vmautoscaling.model.ReplicaPropertiesPost;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GroupProperties
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-25T09:34:22.361740Z[Etc/UTC]")

public class GroupProperties {
  
  public static final String SERIALIZED_NAME_DATACENTER = "datacenter";
  @SerializedName(SERIALIZED_NAME_DATACENTER)
  private GroupPropertiesDatacenter datacenter;


  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private String location;


  public static final String SERIALIZED_NAME_MAX_REPLICA_COUNT = "maxReplicaCount";
  @SerializedName(SERIALIZED_NAME_MAX_REPLICA_COUNT)
  private Long maxReplicaCount;


  public static final String SERIALIZED_NAME_MIN_REPLICA_COUNT = "minReplicaCount";
  @SerializedName(SERIALIZED_NAME_MIN_REPLICA_COUNT)
  private Long minReplicaCount;


  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;


  public static final String SERIALIZED_NAME_POLICY = "policy";
  @SerializedName(SERIALIZED_NAME_POLICY)
  private GroupPolicy policy;


  public static final String SERIALIZED_NAME_REPLICA_CONFIGURATION = "replicaConfiguration";
  @SerializedName(SERIALIZED_NAME_REPLICA_CONFIGURATION)
  private ReplicaPropertiesPost replicaConfiguration;

  

  public GroupProperties datacenter(GroupPropertiesDatacenter datacenter) {
    
    this.datacenter = datacenter;
    return this;
  }

   /**
   * Get datacenter
   * @return datacenter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GroupPropertiesDatacenter getDatacenter() {
    return datacenter;
  }


  public void setDatacenter(GroupPropertiesDatacenter datacenter) {
    this.datacenter = datacenter;
  }



   /**
   * The data center location.
   * @return location
  **/
  @ApiModelProperty(example = "de/txl", required = true, value = "The data center location.")

  public String getLocation() {
    return location;
  }


  public void setLocation(String location) {
    this.location = location;
  }



  public GroupProperties maxReplicaCount(Long maxReplicaCount) {
    
    this.maxReplicaCount = maxReplicaCount;
    return this;
  }

   /**
   * The maximum value for the number of replicas. Must be &gt;&#x3D; 0 and &lt;&#x3D; 100. Will be enforced for both automatic and manual changes.
   * minimum: 0
   * maximum: 100
   * @return maxReplicaCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "10", value = "The maximum value for the number of replicas. Must be >= 0 and <= 100. Will be enforced for both automatic and manual changes.")

  public Long getMaxReplicaCount() {
    return maxReplicaCount;
  }


  public void setMaxReplicaCount(Long maxReplicaCount) {
    this.maxReplicaCount = maxReplicaCount;
  }



  public GroupProperties minReplicaCount(Long minReplicaCount) {
    
    this.minReplicaCount = minReplicaCount;
    return this;
  }

   /**
   * The minimum value for the number of replicas. Must be &gt;&#x3D; 0 and &lt;&#x3D; 100. Will be enforced for both automatic and manual changes
   * minimum: 0
   * maximum: 100
   * @return minReplicaCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "The minimum value for the number of replicas. Must be >= 0 and <= 100. Will be enforced for both automatic and manual changes")

  public Long getMinReplicaCount() {
    return minReplicaCount;
  }


  public void setMinReplicaCount(Long minReplicaCount) {
    this.minReplicaCount = minReplicaCount;
  }



  public GroupProperties name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the VM Auto Scaling Group. This field must not be null or blank.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "VM Auto Scaling Group 1", value = "The name of the VM Auto Scaling Group. This field must not be null or blank.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }



  public GroupProperties policy(GroupPolicy policy) {
    
    this.policy = policy;
    return this;
  }

   /**
   * Get policy
   * @return policy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GroupPolicy getPolicy() {
    return policy;
  }


  public void setPolicy(GroupPolicy policy) {
    this.policy = policy;
  }



  public GroupProperties replicaConfiguration(ReplicaPropertiesPost replicaConfiguration) {
    
    this.replicaConfiguration = replicaConfiguration;
    return this;
  }

   /**
   * Get replicaConfiguration
   * @return replicaConfiguration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ReplicaPropertiesPost getReplicaConfiguration() {
    return replicaConfiguration;
  }


  public void setReplicaConfiguration(ReplicaPropertiesPost replicaConfiguration) {
    this.replicaConfiguration = replicaConfiguration;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupProperties groupProperties = (GroupProperties) o;
    return Objects.equals(this.datacenter, groupProperties.datacenter) && Objects.equals(this.location, groupProperties.location) && Objects.equals(this.maxReplicaCount, groupProperties.maxReplicaCount) && Objects.equals(this.minReplicaCount, groupProperties.minReplicaCount) && Objects.equals(this.name, groupProperties.name) && Objects.equals(this.policy, groupProperties.policy) && Objects.equals(this.replicaConfiguration, groupProperties.replicaConfiguration);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupProperties {\n");
    
    sb.append("    datacenter: ").append(toIndentedString(datacenter)).append("\n");

    sb.append("    location: ").append(toIndentedString(location)).append("\n");

    sb.append("    maxReplicaCount: ").append(toIndentedString(maxReplicaCount)).append("\n");

    sb.append("    minReplicaCount: ").append(toIndentedString(minReplicaCount)).append("\n");

    sb.append("    name: ").append(toIndentedString(name)).append("\n");

    sb.append("    policy: ").append(toIndentedString(policy)).append("\n");

    sb.append("    replicaConfiguration: ").append(toIndentedString(replicaConfiguration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

