/*
 * VM Auto Scaling API
 * The VM Auto Scaling Service enables IONOS clients to horizontally scale the number of VM replicas based on configured rules. You can use VM Auto Scaling to ensure that you have a sufficient number of replicas to handle your application loads at all times.  For this purpose, create a VM Auto Scaling Group that contains the server replicas. The VM Auto Scaling Service ensures that the number of replicas in the group is always within the defined limits.   When scaling policies are set, VM Auto Scaling creates or deletes replicas according to the requirements of your applications. For each policy, specified 'scale-in' and 'scale-out' actions are performed when the corresponding thresholds are reached.
 *
 * The version of the OpenAPI document: 1-SDK.1
 * Contact: support@cloud.ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.vmautoscaling.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ionoscloud.vmautoscaling.model.ActionAmount;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * Defines the action to be performed when the &#39;scaleOutThreshold&#39; is exceeded. Here, scaling is always about adding new VMs to this VM Auto Scaling Group.
 */
@ApiModel(description = "Defines the action to be performed when the 'scaleOutThreshold' is exceeded. Here, scaling is always about adding new VMs to this VM Auto Scaling Group.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-25T09:34:22.361740Z[Etc/UTC]")

public class GroupPolicyScaleOutAction {
  
  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private BigDecimal amount;


  public static final String SERIALIZED_NAME_AMOUNT_TYPE = "amountType";
  @SerializedName(SERIALIZED_NAME_AMOUNT_TYPE)
  private ActionAmount amountType;


  public static final String SERIALIZED_NAME_COOLDOWN_PERIOD = "cooldownPeriod";
  @SerializedName(SERIALIZED_NAME_COOLDOWN_PERIOD)
  private String cooldownPeriod = "5m";

  

  public GroupPolicyScaleOutAction amount(BigDecimal amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * &#39;amountType&#x3D;ABSOLUTE&#39; specifies the absolute number of VMs that are added or removed. The value must be between 1 to 10.   &#39;amountType&#x3D;PERCENTAGE&#39; specifies the percentage value that is applied to the current number of replicas of the VM Auto Scaling Group. The value must be between 1 to 200.   At least one VM is always added or removed.   Note that for &#39;SCALE_IN&#39; operations, volumes are not deleted after the server is deleted.
   * @return amount
  **/
  @ApiModelProperty(example = "1", required = true, value = "'amountType=ABSOLUTE' specifies the absolute number of VMs that are added or removed. The value must be between 1 to 10.   'amountType=PERCENTAGE' specifies the percentage value that is applied to the current number of replicas of the VM Auto Scaling Group. The value must be between 1 to 200.   At least one VM is always added or removed.   Note that for 'SCALE_IN' operations, volumes are not deleted after the server is deleted.")

  public BigDecimal getAmount() {
    return amount;
  }


  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }



  public GroupPolicyScaleOutAction amountType(ActionAmount amountType) {
    
    this.amountType = amountType;
    return this;
  }

   /**
   * Get amountType
   * @return amountType
  **/
  @ApiModelProperty(required = true, value = "")

  public ActionAmount getAmountType() {
    return amountType;
  }


  public void setAmountType(ActionAmount amountType) {
    this.amountType = amountType;
  }



  public GroupPolicyScaleOutAction cooldownPeriod(String cooldownPeriod) {
    
    this.cooldownPeriod = cooldownPeriod;
    return this;
  }

   /**
   * The minimum time that elapses after the start of this scaling action until the following scaling action is started. While a scaling action is in progress, no second action is initiated for the same VM Auto Scaling Group. Instead, the metric is re-evaluated after the current scaling action completes (either successfully or with errors). This is currently validated with a minimum value of 2 minutes and a maximum of 24 hours. The default value is 5 minutes if not specified.
   * @return cooldownPeriod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5m", value = "The minimum time that elapses after the start of this scaling action until the following scaling action is started. While a scaling action is in progress, no second action is initiated for the same VM Auto Scaling Group. Instead, the metric is re-evaluated after the current scaling action completes (either successfully or with errors). This is currently validated with a minimum value of 2 minutes and a maximum of 24 hours. The default value is 5 minutes if not specified.")

  public String getCooldownPeriod() {
    return cooldownPeriod;
  }


  public void setCooldownPeriod(String cooldownPeriod) {
    this.cooldownPeriod = cooldownPeriod;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupPolicyScaleOutAction groupPolicyScaleOutAction = (GroupPolicyScaleOutAction) o;
    return Objects.equals(this.amount, groupPolicyScaleOutAction.amount) && Objects.equals(this.amountType, groupPolicyScaleOutAction.amountType) && Objects.equals(this.cooldownPeriod, groupPolicyScaleOutAction.cooldownPeriod);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupPolicyScaleOutAction {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");

    sb.append("    amountType: ").append(toIndentedString(amountType)).append("\n");

    sb.append("    cooldownPeriod: ").append(toIndentedString(cooldownPeriod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

