/*
 * VM Auto Scaling API
 * The VM Auto Scaling Service enables IONOS clients to horizontally scale the number of VM replicas based on configured rules. You can use VM Auto Scaling to ensure that you have a sufficient number of replicas to handle your application loads at all times.  For this purpose, create a VM Auto Scaling Group that contains the server replicas. The VM Auto Scaling Service ensures that the number of replicas in the group is always within the defined limits.   When scaling policies are set, VM Auto Scaling creates or deletes replicas according to the requirements of your applications. For each policy, specified 'scale-in' and 'scale-out' actions are performed when the corresponding thresholds are reached.
 *
 * The version of the OpenAPI document: 1-SDK.1
 * Contact: support@cloud.ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.vmautoscaling.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * In order to link VM to ALB, target group must be provided
 */
@ApiModel(description = "In order to link VM to ALB, target group must be provided")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-25T09:34:22.361740Z[Etc/UTC]")

public class TargetGroup {
  
  public static final String SERIALIZED_NAME_TARGET_GROUP_ID = "targetGroupId";
  @SerializedName(SERIALIZED_NAME_TARGET_GROUP_ID)
  private String targetGroupId;


  public static final String SERIALIZED_NAME_PORT = "port";
  @SerializedName(SERIALIZED_NAME_PORT)
  private Integer port;


  public static final String SERIALIZED_NAME_WEIGHT = "weight";
  @SerializedName(SERIALIZED_NAME_WEIGHT)
  private Integer weight;

  

  public TargetGroup targetGroupId(String targetGroupId) {
    
    this.targetGroupId = targetGroupId;
    return this;
  }

   /**
   * id
   * @return targetGroupId
  **/
  @ApiModelProperty(example = "id_example", required = true, value = "id")

  public String getTargetGroupId() {
    return targetGroupId;
  }


  public void setTargetGroupId(String targetGroupId) {
    this.targetGroupId = targetGroupId;
  }



  public TargetGroup port(Integer port) {
    
    this.port = port;
    return this;
  }

   /**
   * port
   * @return port
  **/
  @ApiModelProperty(example = "8080", required = true, value = "port")

  public Integer getPort() {
    return port;
  }


  public void setPort(Integer port) {
    this.port = port;
  }



  public TargetGroup weight(Integer weight) {
    
    this.weight = weight;
    return this;
  }

   /**
   * weight
   * @return weight
  **/
  @ApiModelProperty(example = "15", required = true, value = "weight")

  public Integer getWeight() {
    return weight;
  }


  public void setWeight(Integer weight) {
    this.weight = weight;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TargetGroup targetGroup = (TargetGroup) o;
    return Objects.equals(this.targetGroupId, targetGroup.targetGroupId) && Objects.equals(this.port, targetGroup.port) && Objects.equals(this.weight, targetGroup.weight);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TargetGroup {\n");
    
    sb.append("    targetGroupId: ").append(toIndentedString(targetGroupId)).append("\n");

    sb.append("    port: ").append(toIndentedString(port)).append("\n");

    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

